### ISSUE TITLE
The banner file overrides existing one

### ISSUE THREAD

**Issue by heruan** [eriklumme/vaadin-slidetab#1]
Hello @eriklumme and first of all thank you for this useful component, it's well done and works great!

This is not a proper issue per se, but I've found out the `banner.txt` file might override existing ones, e.g. Spring's or in my case the company's one.

This might cause trouble when there are logger observers which track info from the banner, e.g. the app version (or Spring version, in that case).

**Comment by eriklumme** [comment]
I see no reason to keep the `banner.txt`, it's a remnant from the add-on component starter.

I made a new release without it, and will forward this concern to the starter maintainers.

**Comment by heruan** [comment]
Thank you! Is the release `1.0.0.beta2` or `1.0.0.beta4`? The tag says `beta2`, but the description `beta4`.

**Comment by eriklumme** [comment]
`beta4`, I made an erroneous release as I didn't realize I had already released beta2 and beta3 to Vaadin directory. :)

By the way, the `banner.txt` will likely be removed from the add-on component starter, thank you for the feedback!
