### ISSUE TITLE
CSS style for the tab

### ISSUE THREAD

**Issue by JohnnyBeGood70** [eriklumme/vaadin-slidetab#2]
Hi Erik,

Could you tell me how it is possible to style the tab part only? Occasionally I would like to hide the tab with visibility: hidden, keeping the slide only and toggle it with a separate button..

Greetings,

János

**Comment by eriklumme** [comment]
Hi Johnny, sorry to replying so late to this.

With the Vaadin 14 version (2.0.1) it now supports Vaadin's ThemableMixin, so you can use `theme-for` the same way as you would for Vaadin components in V14.
