### ISSUE TITLE
Migration to NPM (Vaadin 14+)

### ISSUE THREAD

**Issue by MojoManagement** [eriklumme/vaadin-slidetab#3]
Hi Erik,

any plan to upgrade to Vaadin 14 / NPM

Regards

**Comment by sajidrs** [comment]
I didn't realize this didn't work with Vaadin 14. 

+1 for upgrade request

**Comment by eriklumme** [comment]
Hi, sorry I haven't replied to this yet, but it works with Vaadin 14 since a month or two back.
